datawarehouse_connect2:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['database2'] %>
  pool: 5
  host: <%= ENV['host2'] %>
  username: <%= ENV['username2'] %>
  password: <%= ENV['password2'] %>